In [103]:
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from xgboost.sklearn import XGBClassifier
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
import xgboost as xgb

In [88]:
df = pd.read_excel("C:/Users/pc/Desktop/20181_all.xlsx")

In [89]:
df['재방문의사'].value_counts()

1    15512
0     6968
Name: 재방문의사, dtype: int64

In [90]:
x_data=df.loc[:,'방한횟수':'D_COU_홍콩']
y_data=df['재방문의사']
x_train, x_test, y_train, y_test =train_test_split(x_data, y_data,test_size=0.25, random_state=0)

In [91]:
print('xtrain shape')
print(x_train.shape)
print('xtest shape')
print(x_test.shape)

xtrain shape
(16860, 140)
xtest shape
(5620, 140)


In [93]:
xgb_model = XGBClassifier()
print(xgb_model.get_xgb_params())

{'base_score': 0.5, 'booster': 'gbtree', 'colsample_bylevel': 1, 'colsample_bynode': 1, 'colsample_bytree': 1, 'gamma': 0, 'learning_rate': 0.1, 'max_delta_step': 0, 'max_depth': 3, 'min_child_weight': 1, 'missing': None, 'n_estimators': 100, 'nthread': 1, 'objective': 'binary:logistic', 'reg_alpha': 0, 'reg_lambda': 1, 'scale_pos_weight': 1, 'seed': 0, 'subsample': 1, 'verbosity': 1}


In [94]:
xgb_model.fit(x_train, y_train, eval_metric=['error'], eval_set=[((x_train, y_train)),(x_test, y_test)])

[0]	validation_0-error:0.247568	validation_1-error:0.25427
[1]	validation_0-error:0.247568	validation_1-error:0.25427
[2]	validation_0-error:0.240866	validation_1-error:0.249288
[3]	validation_0-error:0.242408	validation_1-error:0.249822
[4]	validation_0-error:0.239324	validation_1-error:0.247865
[5]	validation_0-error:0.240332	validation_1-error:0.248577
[6]	validation_0-error:0.240807	validation_1-error:0.249822
[7]	validation_0-error:0.241815	validation_1-error:0.250712
[8]	validation_0-error:0.241637	validation_1-error:0.250712
[9]	validation_0-error:0.241163	validation_1-error:0.250178
[10]	validation_0-error:0.241163	validation_1-error:0.250178
[11]	validation_0-error:0.240391	validation_1-error:0.249644
[12]	validation_0-error:0.240273	validation_1-error:0.249644
[13]	validation_0-error:0.239917	validation_1-error:0.249466
[14]	validation_0-error:0.24051	validation_1-error:0.250712
[15]	validation_0-error:0.237367	validation_1-error:0.247687
[16]	validation_0-error:0.238731	vali

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [95]:
import warnings
warnings.filterwarnings("ignore")

y_pred = xgb_model.predict(x_test)
print('confusion matrix')
print(metrics.confusion_matrix(y_test, y_pred))
print('classification report')
print(metrics.classification_report(y_test, y_pred))

confusion matrix
[[1000  762]
 [ 225 3633]]
classification report
              precision    recall  f1-score   support

           0       0.82      0.57      0.67      1762
           1       0.83      0.94      0.88      3858

    accuracy                           0.82      5620
   macro avg       0.82      0.75      0.77      5620
weighted avg       0.82      0.82      0.81      5620



In [96]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [63]:
rf = RandomForestClassifier(n_estimators=100, oob_score=True, random_state=0)

In [97]:
tree=DecisionTreeClassifier()
tree.fit(x_train,y_train)
print(tree.score(x_train,y_train))
print(tree.score(x_test,y_test))

1.0
0.9676156583629894


In [98]:
y_pred = tree.predict(x_test)
print('confusion matrix')
print(metrics.confusion_matrix(y_test, y_pred))
print('classification report')
print(metrics.classification_report(y_test, y_pred))

confusion matrix
[[1736   26]
 [ 156 3702]]
classification report
              precision    recall  f1-score   support

           0       0.92      0.99      0.95      1762
           1       0.99      0.96      0.98      3858

    accuracy                           0.97      5620
   macro avg       0.96      0.97      0.96      5620
weighted avg       0.97      0.97      0.97      5620



In [99]:
a=tree.feature_importances_

In [100]:
a

array([8.52503410e-03, 3.25359784e-04, 7.98053136e-04, 4.87763053e-04,
       0.00000000e+00, 2.37491623e-02, 3.56503620e-03, 1.32803587e-03,
       2.19865048e-03, 7.24622960e-03, 5.99682620e-03, 2.87712303e-03,
       5.89339207e-03, 1.19037234e-03, 1.86573069e-02, 6.70431299e-03,
       2.71080556e-03, 2.03300005e-02, 3.99509630e-03, 7.74930086e-03,
       2.22117882e-03, 4.32278782e-04, 1.11157401e-03, 2.77604928e-03,
       7.62227436e-04, 9.09341148e-03, 2.05226759e-03, 8.24381298e-04,
       2.55703820e-05, 3.93600001e-03, 2.56859212e-04, 0.00000000e+00,
       2.33834308e-03, 8.13004516e-03, 0.00000000e+00, 2.63562953e-04,
       0.00000000e+00, 2.77893503e-04, 0.00000000e+00, 0.00000000e+00,
       7.53144046e-04, 0.00000000e+00, 5.06596441e-02, 1.06426402e-02,
       1.90979934e-03, 2.19231223e-03, 2.70122787e-04, 2.49542040e-03,
       2.55089826e-03, 2.56658018e-03, 0.00000000e+00, 0.00000000e+00,
       3.29469053e-04, 0.00000000e+00, 5.27084368e-02, 3.10768550e-02,
      

In [106]:
b=pd.DataFrame(a)

In [111]:
b.to_excel("C:/Users/pc/Desktop/ㅅㅅ.xlsx")

In [104]:
estimator = DecisionTreeClassifier(criterion='entropy', max_depth=5, max_leaf_nodes=None, min_samples_split=2, min_samples_leaf=1, max_features=None)

estimator.fit(x_train, y_train)

y_predict = estimator.predict(x_train) 
score = accuracy_score(y_train, y_predict)
print(score) #1.0

y_predict = estimator.predict(x_test) 
score = accuracy_score(y_test, y_predict)
print(score)
score = precision_score(y_test, y_predict)
print(score)
score = recall_score(y_test, y_predict)
print(score)

0.7827402135231317
0.7713523131672598
0.8106737503018595
0.8701399688958009


In [105]:
import os
os.environ["PATH"] += os.pathsep + 'C:/Program Files (x86)/Graphviz2.38/bin'
from sklearn.tree import export_graphviz
export_graphviz(estimator, out_file="./tree.dot", class_names=["0", "1"])

import graphviz
with open("./tree.dot") as f:
    dot_graph = f.read()
dot = graphviz.Source(dot_graph)
dot.format = 'png'
dot.render(filename='tree', directory='./', cleanup=True)
#
#'''
import webbrowser
webbrowser.open('tree.png')

True